let supabaseClient;
let currentGame=null, currentRole=null, currentPlayer=null;
let selectedCharacter='Top Hat', selectedColor='#1769ff', historyFilter='all', subFilter='all';
let realtimeChannel=null;
const BANK='BANK';
const configKey='monopolyCentralBankConfig';
const sessionKey='monopolyCentralBankSession';
const $=id=>document.getElementById(id);
const money=n=>'$'+Number(n||0).toLocaleString();
const cleanCode=s=>(s||'').trim().toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,12);
const tokens=[['Top Hat','🎩'],['Dog','🐶'],['Race Car','🏎️'],['Battleship','🚢'],['Penguin','🐧'],['Dinosaur','🦖'],['Cat','🐱'],['Duck','🦆'],['Wheelbarrow','🛒'],['Thimble','🪡']];
const colors=[['Royal Blue','#1769ff'],['Velvet Purple','#8e44ff'],['Railroad Orange','#ff7a00'],['Boardwalk Gold','#f0b400'],['Ruby Red','#e02834'],['Hot Pink','#e83e8c'],['Aqua Teal','#00a6a6'],['Lime Green','#6abf40'],['Silver Token','#8d99ae'],['Midnight Black','#222222']];
const bankColor='#007a3d';
function escapeHtml(s){return String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),3200)}
function show(id){document.querySelectorAll('main > section.screen').forEach(s=>s.id===id?s.classList.remove('hidden'):s.classList.add('hidden'))}
function goHome(){show('homeCard')}
async function sha(text){const buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function loadConfig(){try{return JSON.parse(localStorage.getItem(configKey)||'{}')}catch{return {}}}
function saveConfig(){const url=$('supabaseUrl').value.trim(), key=$('supabaseKey').value.trim(); if(!url||!key)return toast('Paste Supabase URL and anon key'); localStorage.setItem(configKey,JSON.stringify({url,key})); init();}
function saveSession(obj){localStorage.setItem(sessionKey,JSON.stringify(obj))}
function logout(){localStorage.removeItem(sessionKey); currentGame=null; currentPlayer=null; currentRole=null; show('homeCard'); toast('Logged out on this device')}
function init(){const c=loadConfig(); renderIdentityChoices(); if(c.url&&c.key){supabaseClient=window.supabase.createClient(c.url,c.key); show('homeCard'); tryResume();} else show('setupCard')}
function renderIdentityChoices(taken=[]){if(!$('characterChoices'))return; $('characterChoices').innerHTML=tokens.map(([n,e])=>`<button class="char ${n===selectedCharacter?'active':''}" data-char="${n}"><span>${e}</span>${n}</button>`).join(''); $('colourChoices').innerHTML=colors.map(([n,h])=>`<button class="colour ${h===selectedColor?'active':''} ${taken.includes(h)?'taken':''}" data-color="${h}" style="--c:${h}">${n}</button>`).join('')}
document.addEventListener('click',e=>{const ch=e.target.closest('.char'); if(ch){selectedCharacter=ch.dataset.char; renderIdentityChoices(window.takenColors||[])} const co=e.target.closest('.colour'); if(co&&!co.classList.contains('taken')){selectedColor=co.dataset.color; renderIdentityChoices(window.takenColors||[])}});
function switchJoinMode(mode,el){document.querySelectorAll('.mini-tab').forEach(b=>b.classList.remove('active')); el.classList.add('active'); $('newPlayerPanel').classList.toggle('hidden',mode!=='new'); $('returnPlayerPanel').classList.toggle('hidden',mode!=='return')}
async function fetchGame(code){const {data,error}=await supabaseClient.from('games').select('*').eq('code',code).single(); if(error||!data){toast('Game not found');return null} return data}
async function loadPlayers(code=currentGame.code){const {data,error}=await supabaseClient.from('players').select('*').eq('game_code',code).order('created_at'); if(error){toast('Could not load players. Run the new SQL.'); return []} return data||[]}
async function createGame(){const code=cleanCode($('newGameCode').value), pin=$('newBankerPin').value, starting=Number($('startingMoney').value||1500); if(!code||!pin)return toast('Add game code and banker PIN'); if(starting<1)return toast('Starting money must be above zero'); const {error}=await supabaseClient.from('games').insert({code,banker_pin_hash:await sha(code+':'+pin),starting_money:starting}); if(error)return toast('Game code already exists or SQL is missing'); $('gameCode').value=code; toast('Game created. Share code: '+code)}
async function openLogin(role){const code=cleanCode($('gameCode').value); if(!code)return toast('Enter game code'); currentGame=await fetchGame(code); if(!currentGame)return; currentRole=role; $('loginTitle').textContent=role==='banker'?'Banker Login':'Player Login / Join'; $('bankerLoginPanel').classList.toggle('hidden',role!=='banker'); $('playerLoginPanel').classList.toggle('hidden',role!=='player'); if(role==='player'){const players=await loadPlayers(); window.takenColors=players.map(p=>p.color).filter(Boolean); renderIdentityChoices(window.takenColors); $('returningPlayerSelect').innerHTML=players.map(p=>`<option value="${p.id}">${escapeHtml(p.name)} - ${escapeHtml(p.character||'Token')}</option>`).join('')||'<option>No players yet</option>'} show('loginCard')}
async function confirmBankerLogin(){const pin=$('bankerPinInput').value; if(!pin)return toast('Enter banker PIN'); const hash=await sha(currentGame.code+':'+pin); if(hash!==currentGame.banker_pin_hash)return toast('Wrong banker PIN'); saveSession({role:'banker',code:currentGame.code,pinHash:hash}); await openBanker()}
async function joinGame(){const name=$('joinName').value.trim(), pin=$('joinPin').value; if(!name||!pin)return toast('Add name and PIN'); const players=await loadPlayers(); if(players.some(p=>p.name.toLowerCase()===name.toLowerCase()))return toast('Name already used. Use Returning Player.'); if(players.some(p=>(p.color||'').toLowerCase()===selectedColor.toLowerCase()))return toast('Colour already taken. Pick another.'); const hash=await sha(currentGame.code+':'+pin); const {data,error}=await supabaseClient.from('players').insert({game_code:currentGame.code,name,pin_hash:hash,balance:currentGame.starting_money,character:selectedCharacter,color:selectedColor}).select('*').single(); if(error)return toast('Could not join. Run the new SQL.'); currentPlayer=data; saveSession({role:'player',code:currentGame.code,playerId:data.id,pinHash:hash}); await openPlayer()}
async function confirmPlayerLogin(){const pin=$('returningPin').value, id=$('returningPlayerSelect').value; if(!pin||!id)return toast('Select name and enter PIN'); const players=await loadPlayers(); const p=players.find(x=>String(x.id)===String(id)); const hash=await sha(currentGame.code+':'+pin); if(!p||p.pin_hash!==hash)return toast('Wrong PIN'); currentPlayer=p; saveSession({role:'player',code:currentGame.code,playerId:p.id,pinHash:hash}); await openPlayer()}
async function tryResume(){try{const s=JSON.parse(localStorage.getItem(sessionKey)||'null'); if(!s)return; currentGame=await fetchGame(s.code); if(!currentGame)return; if(s.role==='banker'&&s.pinHash===currentGame.banker_pin_hash){currentRole='banker'; await openBanker(); return} if(s.role==='player'){const players=await loadPlayers(s.code); const p=players.find(x=>String(x.id)===String(s.playerId)); if(p&&p.pin_hash===s.pinHash){currentRole='player'; currentPlayer=p; await openPlayer();}}}catch{}}
function subscribe(){if(realtimeChannel)supabaseClient.removeChannel(realtimeChannel); realtimeChannel=supabaseClient.channel('game-'+currentGame.code).on('postgres_changes',{event:'*',schema:'public',table:'players',filter:'game_code=eq.'+currentGame.code},refreshCurrent).on('postgres_changes',{event:'*',schema:'public',table:'transactions',filter:'game_code=eq.'+currentGame.code},refreshCurrent).subscribe()}
function refreshCurrent(){if(currentRole==='banker')refreshBanker(); if(currentRole==='player')refreshPlayer()}
async function openBanker(){show('bankerCard'); $('bankerGameName').textContent=currentGame.code; await refreshBanker(); subscribe()}
async function openPlayer(){show('playerCard'); await refreshPlayer(); subscribe()}
function playerOpt(p){return `<option value="${p.id}">${tokenEmoji(p.character)} ${escapeHtml(p.name)}</option>`}
async function refreshBanker(){const players=await loadPlayers(); $('fromSelect').innerHTML='<option value="BANK">🏦 BANK</option>'+players.map(playerOpt).join(''); $('toSelect').innerHTML='<option value="BANK">🏦 BANK</option>'+players.map(playerOpt).join(''); $('bankerBalances').innerHTML=players.map(p=>`<div class="vault-card" style="--pc:${p.color}"><div class="token">${tokenEmoji(p.character)}</div><div><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.character||'Token')}</small>${Number(p.balance)===0?'<b class="status">BANKRUPT</b>':''}</div><em>${money(p.balance)}</em></div>`).join('')||'<p>No players joined yet.</p>'; await renderHistory('banker',players)}
async function refreshPlayer(){const {data:p}=await supabaseClient.from('players').select('*').eq('id',currentPlayer.id).single(); if(!p)return; currentPlayer=p; document.documentElement.style.setProperty('--player-color',p.color||'#1769ff'); $('playerBalance').textContent=money(p.balance); $('bankruptBadge').classList.toggle('hidden',Number(p.balance)!==0); $('playerProfile').innerHTML=`<div class="avatar" style="--pc:${p.color}">${tokenEmoji(p.character)}</div><div><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.character||'Token')} • ${colorName(p.color)}</small></div>`; $('identityPreview').innerHTML=`<div class="big-token" style="--pc:${p.color}">${tokenEmoji(p.character)}</div><h2>${escapeHtml(p.name)}</h2><p>${escapeHtml(p.character||'Token')} wrapped in ${colorName(p.color)}. This identity appears on every transaction.</p>`; const players=await loadPlayers(); $('playerToSelect').innerHTML='<option value="BANK">🏦 Bank</option>'+players.filter(x=>x.id!==p.id).map(playerOpt).join(''); $('playerList').innerHTML=players.map(x=>`<div class="player-chip" style="--pc:${x.color}"><span>${tokenEmoji(x.character)}</span><b>${escapeHtml(x.name)}</b></div>`).join(''); await renderHistory('player',players); $('playerSendBtn').disabled=Number(p.balance)===0; if(Number(p.balance)===0)showError('playerError','You are bankrupt. Balance is $0, so you cannot send money until someone pays you.')}
function setPlayerView(v,btn){document.querySelectorAll('#playerCard .nav').forEach(b=>b.classList.remove('active')); if(btn)btn.classList.add('active'); ['Dash','Send','Activity','Identity'].forEach(x=>$('player'+x).classList.toggle('hidden',x.toLowerCase()!==v)); if(v!=='send')hideError('playerError')}
function setPlayerViewByName(v){const i={dash:0,send:1,activity:2,identity:3}[v]; setPlayerView(v,document.querySelectorAll('#playerCard .nav')[i])}
function setBankerView(v,btn){document.querySelectorAll('#bankerCard .nav').forEach(b=>b.classList.remove('active')); if(btn)btn.classList.add('active'); ['Overview','Transfer','Ledger','Settings'].forEach(x=>$('banker'+x).classList.toggle('hidden',x.toLowerCase()!==v))}
function setAmount(id,n){$(id).value=n}
function quickPayBank(){setPlayerViewByName('send'); $('playerToSelect').value='BANK'}
function setHistoryFilter(f){historyFilter=f; $('allTxBtn').classList.toggle('active',f==='all'); $('myTxBtn').classList.toggle('active',f==='mine'); refreshPlayer()}
function setSubFilter(f,btn){subFilter=f; document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); refreshPlayer()}
async function performTransfer(from,to,amount,note,errorId){hideError(errorId); amount=Number(amount); if(!amount||amount<1)return showError(errorId,'Enter an amount above $0.'); if(from===to)return showError(errorId,'Sender and receiver cannot be the same.'); const {error}=await supabaseClient.rpc('perform_monopoly_transaction',{p_game_code:currentGame.code,p_from:from,p_to:to,p_amount:amount,p_note:note||''}); if(error){const m=(error.message||'').includes('INSUFFICIENT_FUNDS')?'Not enough money. You cannot send more money than your current balance. No credit balance is allowed.':error.message; return showError(errorId,m)} toast('Transaction posted')}
async function playerSendMoney(){await performTransfer(String(currentPlayer.id),$('playerToSelect').value,$('playerAmount').value,$('playerNote').value,'playerError'); $('playerAmount').value=''; $('playerNote').value=''}
async function bankerTransfer(){await performTransfer($('fromSelect').value,$('toSelect').value,$('bankerAmount').value,$('bankerNote').value,'bankerError'); $('bankerAmount').value=''; $('bankerNote').value=''}
async function resetGame(){if(!confirm('Reset all player balances to starting money and clear transaction history?'))return; await supabaseClient.from('transactions').delete().eq('game_code',currentGame.code); const players=await loadPlayers(); for(const p of players) await supabaseClient.from('players').update({balance:currentGame.starting_money}).eq('id',p.id); toast('Game reset')}
function showError(id,msg){const el=$(id); el.textContent='⚠️ '+msg; el.classList.remove('hidden')}
function hideError(id){const el=$(id); if(el)el.classList.add('hidden')}
async function renderHistory(mode,players){const {data=[]}=await supabaseClient.from('transactions').select('*').eq('game_code',currentGame.code).order('created_at',{ascending:false}).limit(200); const map=Object.fromEntries(players.map(p=>[String(p.id),p])); let list=data; if(mode==='player'){ if(historyFilter==='mine') list=list.filter(t=>String(t.from_player_id)===String(currentPlayer.id)||String(t.to_player_id)===String(currentPlayer.id)); if(subFilter==='toMe') list=list.filter(t=>String(t.to_player_id)===String(currentPlayer.id)); if(subFilter==='fromMe') list=list.filter(t=>String(t.from_player_id)===String(currentPlayer.id)); if(subFilter==='bank') list=list.filter(t=>t.from_player_id===BANK||t.to_player_id===BANK); $('playerHistory').innerHTML=historyHtml(list,map,true)} else {$('bankerHistory').innerHTML=historyHtml(list,map,false)}}
function historyHtml(list,map,isPlayer){if(!list.length)return '<div class="empty">No transactions yet.</div>'; return list.map(t=>{const from=entity(t.from_player_id,map), to=entity(t.to_player_id,map); const mine=isPlayer&&(String(t.to_player_id)===String(currentPlayer.id)||String(t.from_player_id)===String(currentPlayer.id)); const sign=isPlayer? (String(t.to_player_id)===String(currentPlayer.id)?'+':String(t.from_player_id)===String(currentPlayer.id)?'-':'') : ''; const color=from.color||to.color||bankColor; return `<div class="tx-card ${mine?'mine':''}" style="--pc:${color}"><div class="tx-icon">${from.icon}</div><div class="tx-main"><b>${from.name} → ${to.name}</b><small>${escapeHtml(t.note||'Game transaction')} • ${timeAgo(t.created_at)}</small></div><strong class="amount ${sign==='-'?'neg':'pos'}">${sign}${money(t.amount)}</strong></div>`}).join('')}
function entity(id,map){if(id===BANK)return {name:'Bank',icon:'🏦',color:bankColor}; const p=map[String(id)]||{}; return {name:escapeHtml(p.name||'Player'),icon:tokenEmoji(p.character),color:p.color}}
function tokenEmoji(n){return (tokens.find(x=>x[0]===n)||['','🎲'])[1]}
function colorName(hex){return (colors.find(x=>x[1]===hex)||['Custom'])[0]}
function timeAgo(ts){const s=Math.floor((Date.now()-new Date(ts).getTime())/1000); if(s<60)return s+'s ago'; const m=Math.floor(s/60); if(m<60)return m+'m ago'; const h=Math.floor(m/60); if(h<24)return h+'h ago'; return Math.floor(h/24)+'d ago'}
window.addEventListener('load',init);
